### PR TITLE
chore(*): switch from dep to go mod

### PR DESCRIPTION
**Pull request by hezhizhen**
1. go mod init
2. go mod tidy
3. go mod vendor
4. rm Gopkg*

### CODE REVIEW

**Comment by hezhizhen** [comment]
Which version of Kubernetes should be used?

**Comment by hex108** [comment]
Thanks!

> Which version of Kubernetes should be used?

We'd like to use v1.14.10 which is same as [tapp](https://github.com/tkestack/tapp).

**Comment by hex108** [comment]
Thanks @hezhizhen !

**Comment by hezhizhen** [comment]
> It seems that you did not delete vendor directory.

I'll use v1.14.10 for all Kubernetes related dependencies in the next PR, and remove the vendor directory.

Btw, why not keep the vendor directory?

**Pull request merged**
